
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: clientdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  rust-api:
    build:
      context: ./app/lab_sql_injection
      dockerfile: Dockerfile
    container_name: rust_api_container
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    command: bash -c "cargo run"

volumes:
  mysql_data:
